"""add_consult_logs_table

Revision ID: b825af502e7b
Revises: b3c4d5e6f7a8
Create Date: 2026-04-09 23:10:05.291387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b825af502e7b'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consult_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('selected_place_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consult_logs_user_id'), 'consult_logs', ['user_id'], unique=False)
    op.alter_column('interaction_log', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('uq_places_provider_external'), table_name='places', postgresql_where='(external_id IS NOT NULL)')
    op.create_unique_constraint('uq_places_provider_external', 'places', ['external_provider', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_places_provider_external', 'places', type_='unique')
    op.create_index(op.f('uq_places_provider_external'), 'places', ['external_provider', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    op.alter_column('interaction_log', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_consult_logs_user_id'), table_name='consult_logs')
    op.drop_table('consult_logs')
    # ### end Alembic commands ###
